version: '3.8'

services:
  api:
    build: .
    container_name: album_api
    ports:
      - '3000:3001'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=album_db
    depends_on:
      - postgres
  postgres:
    image: postgres:16.3
    container_name: album_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
# schema e migrations
